name: Build parinfer-rust

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          repository: eraserhd/parinfer-rust
      - run: |
          mkdir -p .cargo/
          echo '[target.x86_64-apple-darwin]' >> .cargo/config
          echo 'linker = "x86_64-apple-darwin14-clang"' >> .cargo/config
          echo 'ar = "x86_64-apple-darwin14-ar"' >> .cargo/config
#      - uses: actions-rs/toolchain@master
#        with:
#          toolchain: stable
#      - name: Install targets
#        run: |
#          sudo apt-get install -y mingw-w64
#          rustup target add x86_64-pc-windows-gnu
#          rustup target add x86_64-unknown-linux-gnu
      - uses: Shogan/rust-musl-action@master
        with:
          args: IFS=":"; read -ra DIRS <<< "$PATH"; ls -1 "${DIRS[@]}"
      - uses: Shogan/rust-musl-action@master
        with:
          args: cargo build --target x86_64-apple-darwin --release
#      - run: ls --almost-all --color=always --classify --group-directories-first --recursive -1 .
      - uses: Shogan/rust-musl-action@master
        with:
          args: cargo build --target x86_64-unknown-linux-musl --release
#      - run: ls --almost-all --color=always --classify --group-directories-first --recursive -1 .
      - uses: Shogan/rust-musl-action@master
        with:
          args: cargo build --target aarch64-unknown-linux-musl --release
      - run: ls --almost-all --color=always --classify --group-directories-first --recursive -1 .
#      - uses: Shogan/rust-musl-action@master
#        with:
#          args: cargo build --target x86_64-pc-windows-gnu --release
#      - run: ls --almost-all --color=always --classify --group-directories-first --recursive -1 .
#      - uses: actions/upload-artifact@v3.1.0
#        with:
#          path: |
#            target/release/libparinfer_rust.dylib
#            target/release/libparinfer_rust.so
#            target/release/parinfer_rust.dll
