name: Build parinfer-rust

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest macOS-latest windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@master
        with:
          repository: eraserhd/parinfer-rust
      - uses: actions-rs/toolchain@master
        with:
          toolchain: stable
      - run: cargo build --release
      - uses: actions/upload-artifact@v3.1.0
        with:
          path: |
            target/release/libparinfer_rust.dylib
            target/release/libparinfer_rust.so
            target/release/parinfer_rust.dll

